"""Question 2 preprocessing: read the shared layer generated by Question 1.

Do not duplicate task tables or read Q1 forecast panels. Create only one
Hour x Region model-input table by combining shared hourly exogenous inputs
with regional static compute parameters.
"""

from __future__ import annotations

from pathlib import Path

import pandas as pd


QUESTION_DIR = Path(__file__).resolve().parent
PROJECT_DIR = QUESTION_DIR.parents[1]
SHARED_DIR = (
    PROJECT_DIR / "question" / "question_01" / "data" / "processed" / "shared"
)
PROCESSED_DIR = QUESTION_DIR / "data" / "processed"
Q2_DIR = PROCESSED_DIR / "q2"

EXOGENOUS_COLUMNS = (
    "Hour",
    "Region",
    "ElectricityPrice_CNY_per_MWh",
    "SellPrice_CNY_per_MWh",
    "CarbonIntensity_tCO2_per_MWh",
    "AvailableRenewable_MW",
    "NonAI_IT_Load_MW",
)
STATIC_COLUMNS = (
    "Region",
    "Available_GPU",
    "Max_IT_Power_MW",
    "PUE",
    "Max_Facility_Power_MW",
)


def _read_shared(filename: str, required_columns: tuple[str, ...]) -> pd.DataFrame:
    path = SHARED_DIR / filename
    if not path.is_file():
        raise FileNotFoundError(
            f"Question 1 shared input is missing: {path}; run question_01/preprocess.py first"
        )
    frame = pd.read_csv(path, encoding="utf-8-sig")
    missing = [column for column in required_columns if column not in frame.columns]
    if missing:
        raise ValueError(f"Shared file {filename} is missing columns: {missing}")
    return frame


def _validate_hour_region(frame: pd.DataFrame, source_name: str) -> None:
    if frame[["Hour", "Region"]].isna().any().any():
        raise ValueError(f"{source_name} contains missing Hour or Region values")
    frame["Hour"] = pd.to_numeric(frame["Hour"], errors="coerce")
    if frame["Hour"].isna().any() or not frame["Hour"].eq(frame["Hour"].round()).all():
        raise ValueError(f"{source_name} Hour values are not valid integers")
    frame["Hour"] = frame["Hour"].astype("int64")
    if not frame["Hour"].between(0, 2406).all():
        raise ValueError(f"{source_name} Hour must be within 0--2406")
    if frame.duplicated(["Hour", "Region"]).any():
        raise ValueError(f"{source_name} contains duplicate Hour x Region records")


def _time_role(hour: int) -> str:
    if hour <= 2399:
        return "main"
    if hour <= 2405:
        return "tail"
    return "terminal"


def _build_region_hour_input(
    region_hour_exogenous: pd.DataFrame,
    region_static_compute: pd.DataFrame,
) -> pd.DataFrame:
    exogenous = region_hour_exogenous.loc[:, list(EXOGENOUS_COLUMNS)].copy()
    static = region_static_compute.loc[:, list(STATIC_COLUMNS)].copy()
    _validate_hour_region(exogenous, "region_hour_exogenous")
    if static["Region"].duplicated().any():
        raise ValueError("region_static_compute Region values must be unique")
    result = exogenous.merge(static, how="left", on="Region", validate="many_to_one")
    if result[list(STATIC_COLUMNS[1:])].isna().any().any():
        raise ValueError("region_static_compute does not cover all hourly region records")
    result["TimeRole"] = result["Hour"].map(_time_role)
    output_columns = [
        "Hour",
        "Region",
        "TimeRole",
        "ElectricityPrice_CNY_per_MWh",
        "SellPrice_CNY_per_MWh",
        "CarbonIntensity_tCO2_per_MWh",
        "AvailableRenewable_MW",
        "NonAI_IT_Load_MW",
        "Available_GPU",
        "Max_IT_Power_MW",
        "PUE",
        "Max_Facility_Power_MW",
    ]
    return result.loc[:, output_columns].sort_values(
        ["Hour", "Region"], kind="stable"
    ).reset_index(drop=True)


def _check_task_shared_objects() -> None:
    tasks = _read_shared("tasks_clean.csv", ("TaskID", "TaskType", "ArrivalHour"))
    candidates = _read_shared(
        "task_candidate_regions.csv",
        ("TaskID", "TaskType", "SourceRegion", "TargetRegion", "NetworkLatency_ms"),
    )
    if tasks["TaskID"].duplicated().any():
        raise ValueError("Shared tasks_clean TaskID values must be unique")
    if not candidates["TaskID"].isin(tasks["TaskID"]).all():
        raise ValueError("Shared task_candidate_regions contains unknown TaskID values")


def main() -> int:
    _check_task_shared_objects()
    region_hour_exogenous = _read_shared(
        "region_hour_exogenous.csv", EXOGENOUS_COLUMNS
    )
    region_static_compute = _read_shared(
        "region_static_compute.csv", STATIC_COLUMNS
    )
    q2_region_hour_input = _build_region_hour_input(
        region_hour_exogenous, region_static_compute
    )
    Q2_DIR.mkdir(parents=True, exist_ok=True)
    q2_region_hour_input.to_csv(
        Q2_DIR / "q2_region_hour_input.csv", index=False, encoding="utf-8-sig"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
